import type { Service } from "@/types/booking";

export const services: Service[] = [
  {
    id: "bridal",
    category: "bridal",
    name: "Mladenačka šminka",
    shortDescription: "Nežna, bezvremenska šminka koja traje od ceremonije do proslave.",
    durationMinutes: 120,
    priceFrom: 180,
    currency: "EUR",
    depositRequired: true,
    depositAmount: 50,
    imageSrc: "/images/services/bridal.jpg",
  },
  {
    id: "soft-glam",
    category: "soft-glam",
    name: "Nežni Glam",
    shortDescription: "Prirodan sjaj. Blaga definicija. Lako i doterano.",
    durationMinutes: 60,
    priceFrom: 140,
    currency: "EUR",
    depositRequired: true,
    depositAmount: 20,
    imageSrc: "/images/services/soft-glam.jpg",
  },
  {
    id: "full-glam",
    category: "full-glam",
    name: "Puni Glam",
    shortDescription: "Izražen pigment, oblikovan kontur — za kameru i za prostoriju.",
    durationMinutes: 75,
    priceFrom: 160,
    currency: "EUR",
    depositRequired: true,
    depositAmount: 20,
    imageSrc: "/images/services/full-glam.jpg",
  },
  {
    id: "editorial",
    category: "editorial",
    name: "Editorijal",
    shortDescription: "Konceptualna umetnost za snimanja, film i kampanje.",
    durationMinutes: 90,
    priceFrom: 200,
    currency: "EUR",
    depositRequired: true,
    depositAmount: 30,
    imageSrc: "/images/services/editorial.jpg",
  },
  {
    id: "education",
    category: "education",
    name: "Edukacija",
    shortDescription: "Praktično usavršavanje, jedan na jedan — tehnika koja postaje instinkt.",
    durationMinutes: 180,
    priceFrom: 250,
    currency: "EUR",
    depositRequired: true,
    depositAmount: 50,
    imageSrc: "/images/services/education.jpg",
  },
];
